# Azure pipelines

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: |
    go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
