# Azure pipelines

trigger:
- master

strategy:
  matrix:
    # linux:
    #  imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: GoTool@0
  inputs:
    version: '1.15.2'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
#- task: GitHubRelease@1
#  inputs:
#    gitHubConnection: 'azure-github'
#    repositoryName: 'dertuxmalwieder/clipurlcleaner'
#    action: 'create'
#    tagSource: userSpecifiedTag  
#    tag: '$(Build.BuildNumber)'  
#    title: '$(Build.BuildNumber)'  
#    changeLogCompareToRelease: 'lastFullRelease'
#    changeLogType: 'commitBased'
#    assets: |
#      $(Build.ArtifactStagingDirectory)/clipurlcleaner*
#      $(Build.ArtifactStagingDirectory)/README.md